name: Generate reports

on:
  # Run if files that could be relevant change.
  push:
    branches:
    - master
    paths:
    - flake.*
    - .github/workflows/gen-report.yml
    - .github/workflows/gen-reports.yml

  schedule:
   - cron: '0 */4 * * *'

jobs:
  nixpkgs-riscv:
    uses: ./.github/workflows/gen-report.yml
    with:
      project: nixpkgs
      jobset: riscv
